### ISSUE TITLE
some problem occured when i initiated qsartuna in jupyter notebook

### ISSUE THREAD

**Issue by luo-yujiang** [MolecularAI/QSARtuna#5]
Hi,
When i test qsartuna after i downloaded it through pip-install, an error occur  
![image](https://github.com/MolecularAI/QSARtuna/assets/74105737/2c921001-4e00-4a59-b36d-219b0f6d4b83)

I found "optunaz" was used in codes, so i edit the file and tried to use "optunaz" but it doesn't work
![image](https://github.com/MolecularAI/QSARtuna/assets/74105737/83c84bd1-590b-4d2a-8e88-b9043c23ca03)

I am not sure whether it's a problem, i reinstalled qsartuna but this error still occured. So i need your assistance.

**Comment by lewismervin1** [comment]
Thanks for the report, this is due to a bug in the Poetry build, which was not installing required packages. 

Please can you recreate the environment with the updated README instracutions?:

`module purge
module load Miniconda3
conda create --name my_env_with_qsartuna python=3.10.10 jupyter pip
conda activate my_env_with_qsartuna
module purge  # Just in case.
which python  # Check. Should output path that contains "my_env_with_qsartuna".
python -m pip install https://github.com/MolecularAI/QSARtuna/files/15091368/qsartuna-3.0.0.1.tar.gz`

**Comment by luo-yujiang** [comment]
Thank you for your reply, my problem is solved
